# Generated by Django 3.2.21 on 2023-09-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='contest_pwd',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contests',
            name='contest_code',
            field=models.CharField(max_length=15),
        ),
    ]
