# Generated by Django 3.2.21 on 2023-09-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_contests_contest_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_contests',
            old_name='contest_id',
            new_name='contest_code',
        ),
        migrations.RenameField(
            model_name='contest_question',
            old_name='contest_id',
            new_name='contest_code',
        ),
        migrations.RenameField(
            model_name='registrations',
            old_name='contest_id',
            new_name='contest_code',
        ),
        migrations.RenameField(
            model_name='submissions',
            old_name='contest_id',
            new_name='contest_code',
        ),
    ]
