# Generated by Django 3.2.21 on 2023-09-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230924_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest_question',
            old_name='contest_code',
            new_name='contest_id',
        ),
    ]
