# Generated by Django 3.2.21 on 2023-09-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_contest_code_contest_question_contest_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_contests',
            old_name='contest_code',
            new_name='contest_id',
        ),
        migrations.RenameField(
            model_name='registrations',
            old_name='contest_code',
            new_name='contest_id',
        ),
        migrations.RenameField(
            model_name='submissions',
            old_name='contest_code',
            new_name='contest_id',
        ),
    ]
