# Generated by Django 3.2.21 on 2023-10-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_sname_users_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='total_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
