# Generated by Django 3.2.21 on 2023-10-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_contests_total_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='users',
            name='otp_expire',
            field=models.DateTimeField(default=None),
        ),
    ]
