# Generated by Django 3.2.21 on 2023-10-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20231013_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='otp_expire',
        ),
    ]
