# Generated by Django 3.2.21 on 2023-10-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_users_otp_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
