# Generated by Django 3.2.21 on 2023-10-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20231014_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='otp',
        ),
    ]
