# Generated by Django 3.2.21 on 2023-10-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_users_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='test_status',
            field=models.IntegerField(default=0, help_text='0=Not Started, 1=Started, 2=Ended'),
        ),
    ]
