# Generated by Django 3.2.21 on 2023-10-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_registrations_test_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='started_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
