# Generated by Django 3.2.21 on 2023-11-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20231107_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='language',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='que_typ',
            field=models.IntegerField(default=0, help_text='0=coding, 1=mcq, 2=debugging'),
        ),
    ]
