# Generated by Django 3.2.21 on 2023-11-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20231107_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='que_typ',
            new_name='que_type',
        ),
    ]
