# Generated by Django 3.2.21 on 2023-11-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_que_typ_questions_que_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='debug_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
