# Generated by Django 3.2.21 on 2023-11-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_questions_debug_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
