# Generated by Django 3.2.21 on 2023-11-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_questions_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='language',
            new_name='debug_language',
        ),
    ]
