# Generated by Django 3.2.21 on 2024-01-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_language_questions_debug_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='contest_type',
            field=models.IntegerField(default=0, help_text='0=codeathon, 1=passing_code, 2=code_wars'),
        ),
    ]
