# Generated by Django 3.2.21 on 2024-01-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_codeduel_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeduel',
            name='opponent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
