# Generated by Django 3.2.21 on 2024-02-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_codeduel_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='email_status',
            field=models.IntegerField(default=0, help_text='0=Not sent, 1=sent before contest, 2=sent after contest'),
        ),
    ]
