# Generated by Django 3.2.21 on 2024-02-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_registrations_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='reg_status',
            field=models.IntegerField(default=0, help_text='0=user_can_register, 1=admin_need_to_approve'),
        ),
    ]
